version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: areal_hr_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2635
      POSTGRES_DB: areal_hr
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./containers/api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:2635@postgres:5432/areal_hr
    depends_on:
      - postgres

volumes:
  pgdata:
